### ISSUE TITLE
Nice framework

### ISSUE THREAD

**Issue by asim** [s8sg/goflow#10]
I have been contemplating ideas around a workflow library for some time, this looks good. I think one question I'd have is, what would a `Flow` interface look like? We want to define that abstraction potentially in Micro as a way of doing orchestration. Once you have enough services this makes sense.

**Comment by s8sg** [comment]
Thank you @asim for checking this out. 

Totally agree, service orchestration something really appealing to me as well. Specially when you have different services and some operation that touches a lot of them, it totally make sense. Like cleaning up users, changing some global attributed, distributed transactions etc.

What are the use cases you are thinking of ?

A flow interface simply could be 
```
Flow {
  String getStartNode()
  []String getNextNodes(String currentNode, String Event)
}
```
Here Node, Event can also be other interfaces

**Comment by s8sg** [comment]
Closing it as its not an issue
