### ISSUE TITLE
Project Activity?

### ISSUE THREAD

**Issue by dubs3c** [s8sg/goflow#11]
Hello, I am very very interested in incorporating goflow into one of my projects. I was just wondering if this repo is still active?

**Comment by s8sg** [comment]
No new feature is actively being developed at the moment. Although for support/bug fix you can always reach out. 
What use case are you thinking ?

**Comment by dubs3c** [comment]
Alright :) well I need to be able to run tasks as a directed graph. Your project seems to accomplish this well. I will do some testing and if I have any questions I can open a new issue.
