### ISSUE TITLE
[QUERY] Examples for conditionalBranch

### ISSUE THREAD

**Issue by Shradha131** [s8sg/goflow#12]
Hey @s8sg 
I was checking the framework to build an aggregator service which calls multiple services and combine results received from each one of them. I was wondering if i can use this framework to achieve below use case 
lets say i have three nodes arranged in series. I want to store the result of intermediate nodes so that on the basis of result, i would decide if i want to proceed to the next node or not. I saw `dag.ConditionalBranch` can achieve so by adding list of conditions. my question is how would you parse response of intermediate nodes? How can we fetch that response from previous node is one defined in my conditionList
I would appreciate if you can give more detailed example of ConditionalBranch

**Comment by s8sg** [comment]
This will be something like

**Comment by s8sg** [comment]
So lets say you have funcA, funcB and funcC
If funcA result is correct you wanna move to funcB, similarly if funcB is correct you wanna move to funcC

Based on this doc [example](https://github.com/s8sg/goflow#conditional-branching),
each conditional node results in a branch with the possible outcomes (here `"pass", "fail"`)
```go
   dag := flow.NewDag()
   dag.Node("funcA").Apply("funcA", funcA)
   funcABranches := dag.ConditionalBranch("result-check", ["pass", "fail"],
       func(response []byte) []string {
             if check_response(response) { return []string{"pass"} } // check response from funcA
             return []string{"failure"}
        }
   )
   dag.Edge("funcA", "result-check")

   // On the pass branch we are performing the `funcB `
   funcABranches["pass"].Node("funcB").Apply("funcB", matchFace)
   funcBBranches := funcABranches["pass"].ConditionalBranch("result-check", ["pass", "fail"],  
        func(response []byte) []string {
             if check_response(response) { return []string{"pass"} } // check response from funcB
             return []string{"failure"}
        }
   )
   funcABranches["pass"].Edge("funcB", "result-check")
   
   // On the pass branch we are performing the `funcC`
   funcBBranches["pass"].Node("funcC").Apply("funcC", matchFace)
```
We didn't define the branch for `fail`, which you can do if you need

**Comment by Shradha131** [comment]
Thanks a lot for the detailed example, it was really helpful. 
Using it, i tried to implement below use-case

![image](https://user-images.githubusercontent.com/30201502/108493905-eb35d280-72cc-11eb-9855-6f2128229718.png)

```

func getUserDetails(data []byte, option map[string][]string) ([]byte, error) {
    return []byte(fmt.Sprintf("")), nil
}

func verifyUserDetails(data []byte, option map[string][]string) ([]byte, error) {
    log.Println(fmt.Sprintf("verify-user \"%s\"", string(data)))
    return []byte(fmt.Sprintf("new")), nil
}

func createWallet(data []byte, option map[string][]string) ([]byte, error) {
    log.Println(fmt.Sprintf("createWallet-user \"%s\"", string(data)))
    return []byte(fmt.Sprintf("")), nil
}

func getWalletDetails(data []byte, option map[string][]string) ([]byte, error) {
    return []byte(fmt.Sprintf("")), nil
}

func userStatusResponse(data []byte) ([]string) {
    status := []string{""}
    status[0] = string(data)
    return status
}


func UserWorkflow(f *flow.Workflow, context *flow.Context) error {
        dag := f.Dag()
        
        dag.Node("get-user").Apply("get-user", getUserDetails)
        dag.Node("verify-user").Apply("verify-user", verifyUserDetails)

        var conditions = []string{"new", "old"}
        branches := dag.ConditionalBranch("user-status", conditions, func(response []byte) []string {
        	resp := userStatusResponse(response)
        	status := []string{"old"}
        	if resp[0] == "new" { status[0] = "new"}
        	return status
        })
        branches["new"].Node("create-wallet").Apply("create-wallet", createWallet)

        dag.Node("get-wallet-details").Apply("get-wallet-details", getWalletDetails)

        dag.Edge("get-user", "verify-user")
        dag.Edge("verify-user", "user-status")
        dag.Edge("user-status", "get-wallet-details")
        return nil
               
}
```
I dont know, why is it showing me 
`[ Failed ] request failed to be processed, failed to execute request. [Request c0nov2rpc98s4b70afdg] Invalid dag, dag has no vertex set`

**Comment by s8sg** [comment]
@Shradha131 Can you check by defining one dummy node for the `branches["old"]` and retry

**Comment by Shradha131** [comment]
@s8sg Thanks a lot, it worked ! 
Please update the document accordingly.

**Comment by s8sg** [comment]
Thanks @Shradha131. Would you like to volunteer for the same ?
Also can you check the behaviour if you have only one condition defined 
```go
var conditions = []string{"new"}
```
And return empty string array instead
```go
func(response []byte) []string {
        	resp := userStatusResponse(response)
        	if resp[0] == "new" { return []string{"new"} }
        	return []string{}
        })
```

**Comment by Shradha131** [comment]
Yes @s8sg, I would :) 
Also it worked fine for above example. 
I got your point, i was sending it in "old" branch node which was undefined.

**Comment by Shradha131** [comment]
I created a PR to update this in README. Please have a look
https://github.com/s8sg/goflow/pull/13

**Comment by s8sg** [comment]
Thanks @Shradha131 for the quick PR. This looks good. I have added a minor comment.

**Comment by Shradha131** [comment]
Hey @s8sg, 
I am unable to see any comment.

**Comment by s8sg** [comment]
I forgot to post the review, can you check once more

**Comment by Shradha131** [comment]
updated the PR

**Comment by s8sg** [comment]
Merged. Closing this issue

**Comment by s8sg** [comment]
Thanks for the PR @Shradha131
