### ISSUE TITLE
[Query] Does goflow has capability of generating workflow diagram on its own? 

### ISSUE THREAD

**Issue by Shradha131** [s8sg/goflow#14]
Hey @s8sg ,

I am wondering if goflow can generate dependency graph of defined workflows, since its using opentracing

**Comment by s8sg** [comment]
@Shradha131 I was working on a dashboard https://github.com/s8sg/goflow-dashboard. But never published it. Can you give it a try and check if this works for you

**Comment by s8sg** [comment]
To answer the question

**Comment by Shradha131** [comment]
Thanks a lot, @s8sg !
I will definitely explore more around it.
Also do you have any examples available of how the dot flow exactly looks?

**Comment by s8sg** [comment]
Any contribution to the dashboard will be very helpful

**Comment by Shradha131** [comment]
Yup, will try to do the same.
