### ISSUE TITLE
Example program needs to be updated

### ISSUE THREAD

**Issue by udayvnayak** [s8sg/goflow#18]
When I try to run the sample program provided, it gives the following errors
./main.go:17:14: cannot use doSomething (type func([]byte, map[string][]string) ([]byte, error)) as type flow.BranchOption in argument to dag.Node

I tried to execute this on "The Go Playground", but it doesn't execute there.

We would like to explore goflow for one of the requirement. Could you please help here

**Comment by cofroute** [comment]
can you tell me about how to solve this problem

**Comment by cofroute** [comment]
> When I try to run the sample program provided, it gives the following errors ./main.go:17:14: cannot use doSomething (type func([]byte, map[string][]string) ([]byte, error)) as type flow.BranchOption in argument to dag.Node
> 
> I tried to execute this on "The Go Playground", but it doesn't execute there.
> 
> We would like to explore goflow for one of the requirement. Could you please help here

can you tell me about how to solve this problem

**Comment by s8sg** [comment]
This can be solved by updating go flow library 
```bash
go get github.com/s8sg/goflow@master
```
