### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by AdrianSeguraOrtiz** [s8sg/goflow#21]
After installing goflow as explained in the guide, I have the following problem:

```sh
$ go build -o goflow
flow.go:6:2: no required module provides package github.com/s8sg/goflow/flow/v1; to add it:
        go get github.com/s8sg/goflow/flow/v1
flow.go:7:2: no required module provides package github.com/s8sg/goflow/v1; to add it:
        go get github.com/s8sg/goflow/v1
```

I try to solve it with the indicated commands but it does not work.

```sh
$ go get github.com/s8sg/goflow/flow/v1
go: module github.com/s8sg/goflow@upgrade found (v0.1.0), but does not contain package github.com/s8sg/goflow/flow/v1
```

Sorry in advance if this is something silly, I am new to learning golang.

**Comment by 578157900** [comment]
modify go.mod 

`require github.com/s8sg/goflow v0.1.1-0.20210813192757-ff43c6d4d624` 

replace 

`require github.com/s8sg/goflow v0.1.0`

**Comment by asjdf** [comment]
exec `go get github.com/s8sg/goflow@master`

**Comment by 578157900** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by s8sg** [comment]
@asjdf @578157900 Can you create an MR to resolve the problem. 
Also would highly appreciate if someone can take a leadership role on usability. 

Specifically to keep support community on 
* Installation
* Use-cases 
* Issues

**Comment by 578157900** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by s8sg** [comment]
@asjdf Lets use this issue to discuss the auto release actions

**Comment by asjdf** [comment]
I thought it is easier for me to explain the new progress by creating a new PR. #43

@s8sg Thank you for this great project

**Comment by s8sg** [comment]
This is merged.

**Comment by 578157900** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
