### ISSUE TITLE
Replace redis with raft consensus

### ISSUE THREAD

**Issue by alphadose** [s8sg/goflow#23]
Redis might become a single point of failure even if redis-sentinel/cluster is used. 
Replacement of redis with https://github.com/hashicorp/raft will remove that single point of failure and enable packaging of goflow into a single binary.
Furthermore, you might find storing and manipulating the DAG easier using the raft protocol as it operates on the basis of replicated state machines.

**Comment by s8sg** [comment]
@alphadose This is not aligned with what go flow is meant to solve. I agree redis is not a good choice. But execution state can be stored some external KeyValue store which uses raft like consul
