### ISSUE TITLE
The latest release does not match github webpage's README.md that causes "does not contain package" error

### ISSUE THREAD

**Issue by xtymbbt** [s8sg/goflow#35]
Firstly, thank you for offering us a very useful tool to build an efficient workflow architecture.

However, when I'm using your github page's README.md's introduction, I encountered this problem:

```shell
github.com/s8sg/goflow/flow/v1: module github.com/s8sg/goflow@latest found (v0.1.0), but does not contain package github.com/s8sg/goflow/flow/v1
github.com/s8sg/goflow/v1: module github.com/s8sg/goflow@latest found (v0.1.0), but does not contain package github.com/s8sg/goflow/v1
```

in my golang project's import, I write this:

```go
import (
	goflow "github.com/s8sg/goflow/v1"
	flow "github.com/s8sg/goflow/flow/v1"
)
```

just the same as your github webpage's README.md write.

So, I went into my local go path where your src code downloaded to find out what happend. In my directory, I found the source code I downloaded is v0.1.0 which is 2020's version and it does not match your latest README instruction. Apparently, the latest release on Github is outdated. So, could you update a latest release that can match your latest README.md?

**Comment by s8sg** [comment]
@xtymbbt Sure. Let me create a new release

**Comment by s8sg** [comment]
@xtymbbt I drafted a new release (v0.1.1), can you check if the issue still persists

**Comment by s8sg** [comment]
This should be fixed with the latest release.

**Comment by xtymbbt** [comment]
Thank you very much for your new release!
