### ISSUE TITLE
Replace redis with etcd support for state saving..

### ISSUE THREAD

**Issue by giorgiozoppi** [s8sg/goflow#39]
Redis has eventual consistentcy that makes inadapt to use when save statistics, a better option is using etcd.

**Comment by s8sg** [comment]
We can refer to this one: https://github.com/faasflow/faas-flow-etcd-statestore/blob/master/etcd.go

**Comment by s8sg** [comment]
Lets  park this for now. It seems the MR by #54 fixes the issue which we primarily discussed the ETCD for
