### ISSUE TITLE
multiplex http port for multiple flows

### ISSUE THREAD

**Issue by asilluron** [s8sg/goflow#6]

**Comment by s8sg** [comment]
@asilluron Can you explain more on the problem and how the requirement helps to solve it ?

**Comment by asilluron** [comment]
Currently, if I want to have a server that I can activate multiple flows on, let's say `add-user` and `delete-user`, I'm writing that as:

```
fs := &goflow.FlowService{
		Port:              8080,
		RedisURL:          "localhost:6379",
		WorkerConcurrency: 5,
	}
	fs.Start("add-user", DefineAddUserWorkflow)
```

and 
```
```
fs := &goflow.FlowService{
		Port:              8081,
		RedisURL:          "localhost:6379",
		WorkerConcurrency: 5,
	}
	fs.Start("delete-user", DefineDeleteUserWorkflow)
```

Then I can curl `localhost:8080` to add and `localhost:8081` to delete

Well, I'd like to multiplex the single HTTP server so I can just call

`localhost:8080/add-user`

and 

`localhost:8080/delete-user`

My current workaround is to run a proxy server in front of the workflow server instances and do the multiplexing that way.

**Comment by s8sg** [comment]
This is added in https://github.com/s8sg/goflow/commit/8ef3fc4eeeba4dd25bb15261b0a4d117a26df965
```go
fs := &goflow.FlowService{
	Port:              8080,
	RedisURL:          "localhost:6379",
	WorkerConcurrency: 5,
}
fs.Register("add-user", DefineAddUserWorkflow)
fs.Register("delete-user", DefineDeleteUserWorkflow)
fs.Start()
```
This will make the two flow available as 
```bash
host:8080/add-user
host:8080/delete-user
```

@asilluron great if you can give it a try

**Comment by asilluron** [comment]
Okay, awesome. I will give it a go.

**Comment by asilluron** [comment]
Seems to work great. I will report any issues or help any way I can if needed.

**Comment by s8sg** [comment]
Great, will close this
