### ISSUE TITLE
Ability to Pause, Resume and Stop

### ISSUE THREAD

**Issue by s8sg** [s8sg/goflow#7]
Add ability to play, pause and Stop a GoFlow, by querying to the individual flow server.

**Comment by 578157900** [comment]
Thinks for you to share this workflow framework. I learn some good things from this codes. But now, I have a question: Will the workflow continue when the service has been restarted? I tested this case, but workflow won't continue. Thx~

**Comment by railic** [comment]
Any updates on this?

**Comment by s8sg** [comment]
Its already implemented, thanks for bringing it to notice
