### ISSUE TITLE
Hi, where is register method?

### ISSUE THREAD

**Issue by thanhpd-teko** [s8sg/goflow#8]
And, is this stable for production use?

**Comment by s8sg** [comment]
Please update to the latest tag v0.0.8

**Comment by thanhpd-teko** [comment]
Yeah, thanks. And do you think it stable for production?

**Comment by thanhpd-teko** [comment]
```
func (fs *FlowService) StartWorker(flowName string, handler runtime.FlowDefinitionHandler) error {
	if flowName == "" {
		return fmt.Errorf("flow-name must not be empty and a unique for each flow")
	}
	fs.ConfigureDefault()
	fs.runtime = &runtime.FlowRuntime{
		Flows:          fs.Flows,
		OpenTracingUrl: fs.OpenTraceUrl,
		RedisURL:       fs.RedisURL,
		DataStore:      fs.DataStore,
		Logger:         fs.Logger,
		Concurrency:    fs.WorkerConcurrency,
	}
	if err := fs.initRuntime(); err != nil {
		return err
	}
	err := fs.runtime.StartQueueWorker()
	return fmt.Errorf("worker has stopped, error: %v", err)
}
```

Here i see, startWorker() method need flowName to start. How to start a worker can handle multiple flows?

**Comment by s8sg** [comment]
Please refer to the [GoDoc](https://godoc.org/github.com/s8sg/goflow#FlowService.Register)

**Comment by thanhpd-teko** [comment]
Worker Mode
Alternatively you can start your GoFlow in worker mode. As a worker GoFlow only handles the workload, and if required you can only scale the workers

```
fs := &goflow.FlowService{
    RedisURL:            "localhost:6379",
    OpenTraceUrl:        "localhost:5775",
    WorkerConcurrency:   5,
}
fs.Register("myflow", DefineWorkflow)
fs.StartWorker()
```
Hi, but your document is quite different.

**Comment by s8sg** [comment]
I see, on worker and server this is still the old contract. Re-opening this

**Comment by s8sg** [comment]
This is fixed in this [commit](https://github.com/s8sg/goflow/commit/9dea44a66e5679d3d822e9bb3b0000c3593dfa06)
